//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Enrollment2 = new HashSet<Enrollment2>();
            this.Videos = new HashSet<Video>();
        }
    
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public string Stream { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ICollection<Enrollment2> Enrollment2 { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
