//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class University2Entities : DbContext
    {
        public University2Entities()
            : base("name=University2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Enrollment2> Enrollment2 { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<PDFFile> PDFFiles { get; set; }
        public virtual DbSet<tblFile> tblFiles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
    
        public virtual ObjectResult<AddToEnrollment_Result> AddToEnrollment(string username, string coursename)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var coursenameParameter = coursename != null ?
                new ObjectParameter("coursename", coursename) :
                new ObjectParameter("coursename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AddToEnrollment_Result>("AddToEnrollment", usernameParameter, coursenameParameter);
        }
    
        public virtual int GetList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetList");
        }
    }
}
